### ISSUE TITLE
Cannot find module 'object-keys'

### ISSUE THREAD

**Issue by jetsetter1** [yeoman/generator-backbone#191]
Trying to create (with seemingly any configuration of options) with prompts on yo v1.0.4  fails with the following error:

```
create     app/scripts/collections/application.js

...

module.js:340
    throw err;
          ^
Error: Cannot find module 'object-keys'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/aden/.nvm/v0.10.22/lib/node_modules/generator-mocha/node_modules/yeoman-generator/node_modules/download/node_modules/through2/node_modules/xtend/index.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by walterspieler** [comment]
@revathskumar  Had the same issue, your solution worked. Thks!
