### ISSUE TITLE
Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'

### ISSUE THREAD

**Issue by ashlinchak** [yeoman/generator-backbone#360]
I can't start working with this generator because I'm getting this error:
```
> node-sass@1.2.3 install /home/user/project/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/user/project/node_modules/grunt-sass/node_modules/node-sass/vendor/linux-x64/binding.node

> node-sass@1.2.3 postinstall /home/user/project/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

`linux-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/user/project/node_modules/grunt-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Linux 3.16.0-46-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```
My environment:
- Ubuntu 14.04 64x
- node 0.12.7
- npm 2.11.3

**Comment by ruyadorno** [comment]
This should be fixed on master.

Let's wait for #357 to confirm it.

**Comment by arthurvr** [comment]
This was fixed in https://github.com/yeoman/generator-backbone/commit/267ad5d475e74ba0568a6b9a292f7aef72d205b2, no reason to keep this open. I'm happy to do the release but don't use this generator myself so want to confirm everything stayed working fine on master.
