### ISSUE TITLE
generator-mocha is a dependency?

### ISSUE THREAD

**Issue by janoskk** [yeoman/generator-backbone#394]
I've just run the backbone generator for the first time and got some strange exceptions, like

```
$ yo backbone
undefined
Out of the box I include HTML5 Boilerplate, jQuery and Backbone.js.
? What more would you like?
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'validate-npm-package-license'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/wizo/.nvm/versions/node/v4.3.2/lib/node_modules/generator-mocha/node_modules/yeoman-generator/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/lib/fixer.js:2:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

After I had installed `generator-mocha` the problem was solved.

**Comment by janoskk** [comment]
Ehh... there was an old version of `yo` in my `$PATH`... ;-)
