### ISSUE TITLE
Cannot find module './utils/escape'

### ISSUE THREAD

**Issue by amitkrgautm** [yeoman/generator-backbone#399]
PS D:\AngularProjectTFS\MagixChat\MagixChat\MxChat> ng serve --open
Cannot find module './utils/escape'
Error: Cannot find module './utils/escape'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\AngularProjectTFS\MagixChat\MagixChat\MxChat\node_modules\copy-webpack-plugin\dist\preProcessPattern.js:16:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\AngularProjectTFS\MagixChat\MagixChat\MxChat\node_modules\copy-webpack-plugin\dist\index.js:7:26)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)

**Comment by amitkrgautm** [comment]
Please Help anyone it's urgent for me...

**Comment by revathskumar** [comment]
@amitkrgautm Not sure why this issue is opened under `generator-backbone` It seems to be you are running a angular project using `ng` cli.
